#!/usr/bin/env bash

curl -LO $(curl -s https://api.github.com/repos/uutils/coreutils/releases/latest | grep -o 'https://[^"]*x86_64-unknown-linux-gnu\.tar\.gz')
tar -xzf coreutils-*-x86_64-unknown-linux-gnu.tar.gz
cp coreutils-*-x86_64-unknown-linux-gnu/coreutils /usr/bin/
chmod +x /usr/bin/coreutils

ln -sf /usr/bin/coreutils /usr/bin/[
ln -sf /usr/bin/coreutils /usr/bin/arch
ln -sf /usr/bin/coreutils /usr/bin/b2sum
ln -sf /usr/bin/coreutils /usr/bin/base32
ln -sf /usr/bin/coreutils /usr/bin/base64
ln -sf /usr/bin/coreutils /usr/bin/basename
ln -sf /usr/bin/coreutils /usr/bin/basenc
ln -sf /usr/bin/coreutils /usr/bin/cat
ln -sf /usr/bin/coreutils /usr/bin/chcon
ln -sf /usr/bin/coreutils /usr/bin/chgrp
ln -sf /usr/bin/coreutils /usr/bin/chmod
ln -sf /usr/bin/coreutils /usr/bin/chown
ln -sf /usr/bin/coreutils /usr/bin/chroot
ln -sf /usr/bin/coreutils /usr/bin/cksum
ln -sf /usr/bin/coreutils /usr/bin/comm
ln -sf /usr/bin/coreutils /usr/bin/cp
ln -sf /usr/bin/coreutils /usr/bin/csplit
ln -sf /usr/bin/coreutils /usr/bin/cut
ln -sf /usr/bin/coreutils /usr/bin/date
ln -sf /usr/bin/coreutils /usr/bin/dd
ln -sf /usr/bin/coreutils /usr/bin/df
ln -sf /usr/bin/coreutils /usr/bin/dir
ln -sf /usr/bin/coreutils /usr/bin/dircolors
ln -sf /usr/bin/coreutils /usr/bin/dirname
ln -sf /usr/bin/coreutils /usr/bin/du
ln -sf /usr/bin/coreutils /usr/bin/echo
ln -sf /usr/bin/coreutils /usr/bin/env
ln -sf /usr/bin/coreutils /usr/bin/expand
ln -sf /usr/bin/coreutils /usr/bin/expr
ln -sf /usr/bin/coreutils /usr/bin/factor
ln -sf /usr/bin/coreutils /usr/bin/false
ln -sf /usr/bin/coreutils /usr/bin/fmt
ln -sf /usr/bin/coreutils /usr/bin/fold
ln -sf /usr/bin/coreutils /usr/bin/groups
ln -sf /usr/bin/coreutils /usr/bin/head
ln -sf /usr/bin/coreutils /usr/bin/hostid
ln -sf /usr/bin/coreutils /usr/bin/id
ln -sf /usr/bin/coreutils /usr/bin/install
ln -sf /usr/bin/coreutils /usr/bin/join
ln -sf /usr/bin/coreutils /usr/bin/link
ln -sf /usr/bin/coreutils /usr/bin/ln
ln -sf /usr/bin/coreutils /usr/bin/logname
ln -sf /usr/bin/coreutils /usr/bin/ls
ln -sf /usr/bin/coreutils /usr/bin/md5sum
ln -sf /usr/bin/coreutils /usr/bin/mkdir
ln -sf /usr/bin/coreutils /usr/bin/mkfifo
ln -sf /usr/bin/coreutils /usr/bin/mknod
ln -sf /usr/bin/coreutils /usr/bin/mktemp
ln -sf /usr/bin/coreutils /usr/bin/more
ln -sf /usr/bin/coreutils /usr/bin/mv
ln -sf /usr/bin/coreutils /usr/bin/nice
ln -sf /usr/bin/coreutils /usr/bin/nl
ln -sf /usr/bin/coreutils /usr/bin/nohup
ln -sf /usr/bin/coreutils /usr/bin/nproc
ln -sf /usr/bin/coreutils /usr/bin/numfmt
ln -sf /usr/bin/coreutils /usr/bin/od
ln -sf /usr/bin/coreutils /usr/bin/paste
ln -sf /usr/bin/coreutils /usr/bin/pathchk
ln -sf /usr/bin/coreutils /usr/bin/pinky
ln -sf /usr/bin/coreutils /usr/bin/pr
ln -sf /usr/bin/coreutils /usr/bin/printenv
ln -sf /usr/bin/coreutils /usr/bin/printf
ln -sf /usr/bin/coreutils /usr/bin/ptx
ln -sf /usr/bin/coreutils /usr/bin/pwd
ln -sf /usr/bin/coreutils /usr/bin/readlink
ln -sf /usr/bin/coreutils /usr/bin/realpath
ln -sf /usr/bin/coreutils /usr/bin/rm
ln -sf /usr/bin/coreutils /usr/bin/rmdir
ln -sf /usr/bin/coreutils /usr/bin/runcon
ln -sf /usr/bin/coreutils /usr/bin/seq
ln -sf /usr/bin/coreutils /usr/bin/sha1sum
ln -sf /usr/bin/coreutils /usr/bin/sha224sum
ln -sf /usr/bin/coreutils /usr/bin/sha256sum
ln -sf /usr/bin/coreutils /usr/bin/sha384sum
ln -sf /usr/bin/coreutils /usr/bin/sha512sum
ln -sf /usr/bin/coreutils /usr/bin/shred
ln -sf /usr/bin/coreutils /usr/bin/shuf
ln -sf /usr/bin/coreutils /usr/bin/sleep
ln -sf /usr/bin/coreutils /usr/bin/sort
ln -sf /usr/bin/coreutils /usr/bin/split
ln -sf /usr/bin/coreutils /usr/bin/stat
ln -sf /usr/bin/coreutils /usr/bin/stdbuf
ln -sf /usr/bin/coreutils /usr/bin/stty
ln -sf /usr/bin/coreutils /usr/bin/sum
ln -sf /usr/bin/coreutils /usr/bin/sync
ln -sf /usr/bin/coreutils /usr/bin/tac
ln -sf /usr/bin/coreutils /usr/bin/tail
ln -sf /usr/bin/coreutils /usr/bin/tee
ln -sf /usr/bin/coreutils /usr/bin/test
ln -sf /usr/bin/coreutils /usr/bin/timeout
ln -sf /usr/bin/coreutils /usr/bin/touch
ln -sf /usr/bin/coreutils /usr/bin/tr
ln -sf /usr/bin/coreutils /usr/bin/true
ln -sf /usr/bin/coreutils /usr/bin/truncate
ln -sf /usr/bin/coreutils /usr/bin/tsort
ln -sf /usr/bin/coreutils /usr/bin/tty
ln -sf /usr/bin/coreutils /usr/bin/uname
ln -sf /usr/bin/coreutils /usr/bin/unexpand
ln -sf /usr/bin/coreutils /usr/bin/uniq
ln -sf /usr/bin/coreutils /usr/bin/unlink
ln -sf /usr/bin/coreutils /usr/bin/users
ln -sf /usr/bin/coreutils /usr/bin/vdir
ln -sf /usr/bin/coreutils /usr/bin/wc
ln -sf /usr/bin/coreutils /usr/bin/who
ln -sf /usr/bin/coreutils /usr/bin/whoami
ln -sf /usr/bin/coreutils /usr/bin/yes
