---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-niri
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: dnf
    repos:
      copr:
        - nett00n/hyprland
        - v8v88v8v88/helium
        - yalter/niri
    install:
      packages:
        - niri
        - swayidle
        - swaybg
        - mako
        - hyprlock
        - xwayland-satellite
        - foot
        - nautilus
        - nautilus-extensions
        - papers-nautilus
        - papers-previewer
        - papers-thumbnailer
        - nmtui
        - kernel-tools
        - sudo-rs
        - ntpd-rs
        - imv
        - helium
        - wlsunset
        - gvfs-mtp
        - libatomic
      exclude:
        - alacritty
        - fuzzel
        - waybar
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - chrony
        - initscripts-service
        - dhcp-client
        - nano
  #- type: default-flatpaks
  #  configurations:
  #    - notify: true # Send notification after install/uninstall is finished (true/false)
  #      scope: system
  #      # If no repo information is specified, Flathub will be used by default
  #      install: # system flatpaks we want all users to have and not remove
  #        - org.gnome.Loupe
  #    - scope: user # Also add Flathub user repo, but no user packages
  - type: script
    scripts:
    - custom-kernel.sh
    - sudo-rs.sh
  - type: git
    source: local
    packages:
      - repo: uutils/coreutils
        files:
        - coreutils
        postinstall: |
          for cmd in $(coreutils --list); do
            ln -sf /usr/bin/coreutils "/usr/bin/$cmd"
          done
      - repo: uutils/findutils
        files:
          - find
          - locate
          - updatedb
          - xargs
      - repo: uutils/red
        postinstall: ln -sf /usr/bin/red /usr/bin/sed
      - repo: Mjoyufull/fsel
      - repo: fish-shell/fish-shell
      - repo: reubeno/brush
        postinstall: ln -sf /usr/bin/brush /usr/bin/bash
      - repo: yt-dlp/yt-dlp
        type: share
        regex: yt-dlp_linux.zip
        folder: yt-dlp
        postinstall: ln -s /usr/share/yt-dlp/yt-dlp_linux /usr/bin/yt-dlp
  - type: systemd
    system:
      enabled:
        - ntpd-rs
  - type: signing
